# Generated by Django 3.2.8 on 2021-10-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileutils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name_plural': '파일 게시판'},
        ),
    ]
