# Generated by Django 3.2.8 on 2021-10-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileutils', '0002_alter_fileupload_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
