# Generated by Django 3.2.7 on 2021-12-23 02:39

from django.db import migrations, models
import fileutils.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileutils', '0005_alter_fileuploadcsv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadcsv',
            name='file',
            field=models.FileField(null=True, storage=fileutils.models.OverwriteStorage(), upload_to=fileutils.models.get_random_filename),
        ),
    ]
