# Generated by Django 3.2.7 on 2021-12-22 02:36

from django.db import migrations, models
import fileutils.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileutils', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadcsv',
            name='file',
            field=models.FileField(null=True, storage=fileutils.models.OverwriteStorage(), upload_to=''),
        ),
    ]
