# Generated by Django 3.2.7 on 2021-11-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sch_color', models.CharField(max_length=50)),
                ('x_axis_1', models.CharField(max_length=100)),
                ('y_axis_1', models.CharField(max_length=100)),
                ('x_axis_2', models.CharField(max_length=100)),
                ('y_axis_2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
